{
  "debugCompile": false,
  "debugRun": false,
  "showCode": false,
  "measureTime": false,
  "useEmpty": false,
  "translateDigits": false,
  "verboseResult": false,
  "decimalPoint": ".",
  "thousandsSep": ",",
  "posSign": "+",
  "negSign": "+",
  "encoding": 2,
  "logEncoding": 2,
  "maxFileSize": 1000,
  "patternNearest": 2,
  "patternBlock": 100,
  "positionType": 1,
  "logChannel": "default",
  "pdfReader": "pdftotext",
  "frmReader": "pandoc",
  "appPath": "~/.config/scripal",
  "sentenceEnd": [ ".", "!", "?" ],
  "separators": [ " ", ".", "!", "?", ",", ";", ":", "/", "(", ")", "[", "]", "{", "}" ],
  "abbreviations": [  ]
  }